version: 2
updates:
  - package-ecosystem: github-actions
    directories:
      - "/"
      - "/actions/**"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    cooldown:
      default-days: 7
  - package-ecosystem: pip
    directories:
      - "/actions/**"
    groups:
      copier:
        patterns:
          - copier
        group-by: dependency-name
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    cooldown:
      default-days: 7
