name: 'Configure Mkdocs for GitHub Pages'
description: 'A GitHub Action to enable mkdocs for Pages and extract various metadata about a site.'

runs:
  using: 'composite'
  steps:
    - name: Setup mkdocs config
      shell: bash
      run: |
        bash "${{ github.action_path }}/setup_mkdocs.sh"
