name: Release draft
description: Create or update a draft release from provided name/tag/changelog.
inputs:
  token:
    description: GitHub token used to draft the release.
    required: true
  name:
    description: Release name.
    required: true
  tag-name:
    description: Release tag name.
    required: true
  changelog:
    description: Changelog body used for release notes.
    required: true
outputs:
  id:
    description: The release ID.
    value: ${{ steps.upsert.outputs.id }}
  name:
    description: The release name.
    value: ${{ steps.upsert.outputs.name }}
  tag-name:
    description: The release tag name.
    value: ${{ steps.upsert.outputs.tag-name }}
  html-url:
    description: The HTML URL for the release.
    value: ${{ steps.upsert.outputs.html-url }}
  upload-url:
    description: The upload URL for release assets.
    value: ${{ steps.upsert.outputs.upload-url }}
runs:
  using: composite
  steps:
    - name: Create or update draft release
      id: upsert
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
        TAG_NAME: ${{ inputs.tag-name }}
        RELEASE_NAME: ${{ inputs.name }}
        CHANGELOG: ${{ inputs.changelog }}
      run: |
        set -euo pipefail
        RELEASE_JSON="$(bash "${{ github.action_path }}/upsert_draft_release.sh")"
        echo "id=$(jq -r '.id' <<< "$RELEASE_JSON")" >> "$GITHUB_OUTPUT"
        echo "name=$(jq -r '.name' <<< "$RELEASE_JSON")" >> "$GITHUB_OUTPUT"
        echo "tag-name=$(jq -r '.tag_name' <<< "$RELEASE_JSON")" >> "$GITHUB_OUTPUT"
        echo "html-url=$(jq -r '.html_url' <<< "$RELEASE_JSON")" >> "$GITHUB_OUTPUT"
        echo "upload-url=$(jq -r '.upload_url' <<< "$RELEASE_JSON")" >> "$GITHUB_OUTPUT"
