name: Release draft
description: Draft release notes for your next release based on merged PRs.
inputs:
  gh_token:
    description: GitHub token used to draft the release.
    required: true
  name:
    description: Optional explicit release name override.
    required: false
    default: ""
  tag_name:
    description: Optional explicit tag name override.
    required: false
    default: ""
outputs:
  id:
    description: The release ID.
    value: ${{ steps.upsert-release.outputs.id }}
  name:
    description: The release name.
    value: ${{ steps.upsert-release.outputs.name }}
  tag_name:
    description: The tag name of the drafted release.
    value: ${{ steps.upsert-release.outputs.tag_name }}
  html_url:
    description: The HTML URL for the release.
    value: ${{ steps.upsert-release.outputs.html_url }}
  upload_url:
    description: The upload URL for release assets.
    value: ${{ steps.upsert-release.outputs.upload_url }}
  body:
    description: The generated release notes body.
    value: ${{ steps.upsert-release.outputs.body }}
  resolved_version:
    description: The resolved semantic version.
    value: ${{ steps.resolve-version.outputs.resolved_version }}
runs:
  using: composite
  steps:
    - name: Checkout repository history
      uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Install Python dependencies
      shell: bash
      run: |
        python3 -m pip install --quiet pyyaml

    - name: Resolve changelog base
      id: changelog-base
      shell: bash
      run: |
        BASE_JSON="$(python3 "${{ github.action_path }}/resolve_next_version.py" --mode base)"
        echo "from_ref=$(jq -r '.from_ref' <<< "$BASE_JSON")" | tee -a "$GITHUB_OUTPUT"

    - name: Build changelog
      id: changelog
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.gh_token }}
        REPO: ${{ github.repository }}
        FROM_REF: ${{ steps.changelog-base.outputs.from_ref }}
        TO_REF: ${{ github.sha }}
        RELEASE_DRAFTER_CONFIG: ${{ github.action_path }}/release-drafter.yml
      run: |
        CHANGELOG_JSON="$(python3 "${{ github.action_path }}/build_changelog.py")"
        echo "pull_requests=$(jq -r '.pull_requests' <<< "$CHANGELOG_JSON")" | tee -a "$GITHUB_OUTPUT"
        {
          echo "changelog<<EOF_RELEASE_DRAFT_CHANGELOG"
          jq -r '.changelog' <<< "$CHANGELOG_JSON"
          echo "EOF_RELEASE_DRAFT_CHANGELOG"
        } | tee -a "$GITHUB_OUTPUT"

    - name: Resolve next version
      id: resolve-version
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.gh_token }}
        REPO: ${{ github.repository }}
        FROM_TAG: ${{ steps.changelog-base.outputs.from_ref }}
        PR_IDS: ${{ steps.changelog.outputs.pull_requests }}
        RELEASE_DRAFTER_CONFIG: ${{ github.action_path }}/release-drafter.yml
      run: |
        VERSION_JSON="$(python3 "${{ github.action_path }}/resolve_next_version.py" --mode next)"
        echo "tag_name=$(jq -r '.tag_name' <<< "$VERSION_JSON")" | tee -a "$GITHUB_OUTPUT"
        echo "release_name=$(jq -r '.release_name' <<< "$VERSION_JSON")" | tee -a "$GITHUB_OUTPUT"
        echo "resolved_version=$(jq -r '.resolved_version' <<< "$VERSION_JSON")" | tee -a "$GITHUB_OUTPUT"

    - name: Resolve tag name override
      id: resolve-tag-name
      shell: bash
      run: |
        echo "tag_name=${{ inputs.tag_name || steps.resolve-version.outputs.tag_name }}" | tee -a "$GITHUB_OUTPUT"

    - name: Resolve release name override
      id: resolve-release-name
      shell: bash
      run: |
        echo "name=${{ inputs.name || steps.resolve-version.outputs.release_name }}" | tee -a "$GITHUB_OUTPUT"

    - name: Create or update draft release
      id: upsert-release
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.gh_token }}
        TAG_NAME: ${{ steps.resolve-tag-name.outputs.tag_name }}
        RELEASE_NAME: ${{ steps.resolve-release-name.outputs.name }}
        CHANGELOG: ${{ steps.changelog.outputs.changelog }}
      run: |
        RELEASE_JSON="$(bash "${{ github.action_path }}/upsert_draft_release.sh")"
        echo "id=$(jq -r '.id' <<< "$RELEASE_JSON")" | tee -a "$GITHUB_OUTPUT"
        echo "name=$(jq -r '.name' <<< "$RELEASE_JSON")" | tee -a "$GITHUB_OUTPUT"
        echo "tag_name=$(jq -r '.tag_name' <<< "$RELEASE_JSON")" | tee -a "$GITHUB_OUTPUT"
        echo "html_url=$(jq -r '.html_url' <<< "$RELEASE_JSON")" | tee -a "$GITHUB_OUTPUT"
        echo "upload_url=$(jq -r '.upload_url' <<< "$RELEASE_JSON")" | tee -a "$GITHUB_OUTPUT"
        {
          echo "body<<EOF_RELEASE_DRAFT_BODY"
          jq -r '.body' <<< "$RELEASE_JSON"
          echo "EOF_RELEASE_DRAFT_BODY"
        } | tee -a "$GITHUB_OUTPUT"
