name: Release draft
description: Draft release notes for your next release based on merged PRs.
inputs:
  github_token:
    description: GitHub token used to draft the release.
    required: true
  tag-suffix:
    description: Optional suffix appended to tag-template (test/debug use).
    required: false
    default: ""
outputs:
  tag_name:
    description: The tag name of the drafted release.
    value: ${{ steps.release-draft.outputs.tag_name }}
runs:
  using: composite
  steps:
    - name: Setup release-drafter config
      shell: bash
      run: |
        mkdir -p .github
        cp "${{ github.action_path }}/release-drafter.yml" .github/release-drafter.yml
        python3 - "$PWD/.github/release-drafter.yml" "${{ inputs.tag-suffix }}" <<'PY'
        import sys
        from pathlib import Path

        config_path = Path(sys.argv[1])
        tag_suffix = sys.argv[2]

        lines = config_path.read_text(encoding="utf-8").splitlines()
        out = []
        for line in lines:
            if tag_suffix and line.startswith('tag-template: "') and line.endswith('"'):
                base = line[len('tag-template: "'):-1]
                suffix = tag_suffix.replace('"', '\\"')
                line = f'tag-template: "{base}{suffix}"'
            out.append(line)

        config_path.write_text("\n".join(out) + "\n", encoding="utf-8")
        PY
    - uses: release-drafter/release-drafter@v5.20.0
      id: release-draft
      with:
        config-name: release-drafter.yml
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
