name: Draft release

on:
  workflow_call:
    inputs:
      github_token:
        description: 'GitHub token used to draft the release.'
        required: false
        type: string
      bump_script:
        description: 'The script to run to bump the version.'
        required: false
        default: ''
        type: string

permissions:
  contents: write # Needed to publish a draft release
  pull-requests: write # Needed to create a version bump PR

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.release-draft.outputs.tag_name }}
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "main"
      - uses: athackst/buildsmith/actions/release-draft@main
        id: release-draft
        with:
          github_token: ${{ inputs.github_token != '' && inputs.github_token || github.token }}

  bump_version:
    if: ${{ inputs.bump_script != '' }}
    runs-on: ubuntu-latest
    needs: update_release_draft
    env:
      VERSION: ${{ needs.update_release_draft.outputs.tag_name }}
    steps:
      - uses: actions/checkout@v4
      # Version bump
      - name: Bump version
        run: |
          echo "Bumping version to ${VERSION}"
          ${BUMP_SCRIPT} ${VERSION}
        env:
          BUMP_SCRIPT: ${{ inputs.bump_script }}
      - name: Create pull request
        uses: peter-evans/create-pull-request@v5
        id: cpr
        with:
          token: ${{ inputs.github_token != '' && inputs.github_token || github.token }}
          commit-message: Bump version to ${{ needs.update_release_draft.outputs.tag_name }}
          title: Bump version to ${{ needs.update_release_draft.outputs.tag_name }}
          body: |
            Bump version to ${{ needs.update_release_draft.outputs.tag_name }}
          branch: skip/version-bump-${{ needs.update_release_draft.outputs.tag_name }}
          labels: |
            version-bump
            skip-changelog
