name: Build a Jekyll Site

on:
  workflow_call:
    inputs:
      source:
        description: Optional source directory for the site
        type: string
        required: false
        default: "."
      version:
        description: Optional Version identifier to publish, for example 1.2.3
        type: string
        required: false
        default: ""
      semiliterate:
        description: Extract docs with semiliterate
        type: boolean
        required: false
        default: true
      artifact-name:
        description: "Artifact name for the built site."
        type: string
        required: false
        default: "github-pages"
    outputs:
      host:
        description: The host name for the site
        value: ${{ jobs.build-site.outputs.host }}
      base-path:
        description: The base-path for the site
        value: ${{ jobs.build-site.outputs.base-path }}
      base-url:
        description: The base url for the site
        value: ${{ jobs.build-site.outputs.base-url }}
      version:
        description: The version number
        value: ${{ jobs.build-site.outputs.version }}
      artifact-name:
        description: The name of the site artifact
        value: ${{ jobs.build-site.outputs.artifact-name }}

jobs:
  build-site:
    runs-on: ubuntu-latest
    outputs:
      host: ${{ steps.settings.outputs.host }}
      base-path: ${{ steps.settings.outputs.base_path }}
      base-url: ${{ steps.settings.outputs.base_url }}
      version: ${{ steps.settings.outputs.version }}
      artifact-name: ${{ inputs.artifact-name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v6

      - name: Settings
        id: settings
        run: |
          set -euo pipefail
          version="${{ inputs.version }}"
          echo "version=${version}" | tee -a "$GITHUB_OUTPUT"

          base_path="${{ steps.pages.outputs.base_path }}"
          base_url="${{ steps.pages.outputs.base_url }}"
          if [ -n "$version" ]; then
            base_path="${base_path}/${version}"
            base_url="${base_url}/${version}"
          fi
          echo "base_path=${base_path}" | tee -a "$GITHUB_OUTPUT"
          echo "base_url=${base_url}" | tee -a "$GITHUB_OUTPUT"

          host="${{ steps.pages.outputs.host }}"
          echo "host=${host}" | tee -a "$GITHUB_OUTPUT"

      - name: Configure Jekyll site
        uses: athackst/ci/actions/jekyll-config@main

      - name: Extract with semiliterate
        if: ${{ inputs.semiliterate }}
        id: semiliterate
        uses: PrimerPages/semiliterate@main
        with:
          source: ${{ inputs.source }}
          out: jekyll-site

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1.306.0
        with:
          ruby-version: 3.3.4
          bundler-cache: true

      - name: Build with Jekyll
        # Outputs to the './_site' directory by default
        env:
          JEKYLL_ENV: production
          JEKYLL_GITHUB_TOKEN: ${{ github.token }}
          BASEURL: ${{ steps.settings.outputs.base_path }}
          SOURCE: ${{ steps.semiliterate.outputs.out  || '.' }}
        run: bundle exec jekyll build --baseurl "${BASEURL}" --source "${SOURCE}"

      - name: Debug output
        run: |
          tree _site
          cat _site/index.html

      - name: Upload artifact
        id: artifact
        uses: actions/upload-pages-artifact@v5
        with:
          name: ${{ inputs.artifact-name }}
          path: _site
