name: MkDocs Site
on:
  workflow_call:
    inputs:
      version:
        description: "Optional version of deployment."
        type: string
        required: false
        default: ""
      artifact-name:
        description: "Artifact name for the built site."
        type: string
        required: false
        default: "github-pages"
    outputs:
      host:
        description: The host name for the site
        value: ${{ jobs.build-site.outputs.host }}
      base-path:
        description: The base-path for the site
        value: ${{ jobs.build-site.outputs.base-path }}
      base-url:
        description: The base url for the site
        value: ${{ jobs.build-site.outputs.base-url }}
      version:
        description: The version number
        value: ${{ jobs.build-site.outputs.version }}
      artifact-name:
        description: The name of the site artifact
        value: ${{ jobs.build-site.outputs.artifact-name }}

jobs:
  build-site:
    runs-on: ubuntu-latest
    outputs:
      host: ${{ steps.pages.outputs.host }}
      base-path: ${{ steps.pages.outputs.base_path }}
      base-url: ${{ steps.pages.outputs.base_url }}
      version: ${{ inputs.version }}
      artifact-name: ${{ inputs.artifact-name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.0

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v6

      - name: Setup mkdocs config
        uses: athackst/ci/actions/mkdocs-config@main

      - name: Debug MkDocs configuration
        shell: bash
        run: |
          if [ -f mkdocs.yml ]; then
            cat mkdocs.yml
          else
            echo "mkdocs.yml was not generated."
          fi

      - name: Build docs
        id: mkdocs
        uses: athackst/mkdocs-simple-plugin@main
        with:
          push: false
          site_url: ${{ steps.pages.outputs.base_url }}${{ inputs.version != '' && format('/{0}', inputs.version) || '' }}

      - name: Debug output
        run: |
          tree site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          name: ${{ inputs.artifact-name }}
          path: ./site
