name: PR labeler
on:
  workflow_call:

jobs:
  pr-labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: athackst/ci/actions/labeler@main
        with:
          github_token: ${{ github.token }}
